name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up Gox
      run: |
        go get github.com/mitchellh/gox
        go get
        
    - name: Go Build
      run: |
        gox -osarch=darwin/386
        gox -osarch=darwin/amd64
        gox -osarch=linux/amd64
        gox -osarch=linux/386
        gox -osarch=windows/amd64
        gox -osarch=windows/386
        
    - name: Ls
      run: ls -al

           
